general {
    # Make sure there is at most one hyprlock instance
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = niri msg action power-on-monitors
}

# Dim the screen before locking
# NOTE: brightnessctl works only with laptop screen
listener {
    timeout = 60
    on-timeout = brightnessctl --save set 30%
    on-resume = brightnessctl --restore
}

# Fallback to notification when connected to external monitor
# TODO: Setup ddcutil with udev i2c rules for external monitors
# See https://www.ddcutil.com/i2c_permissions/
# Could also consider using ddccontrol
listener {
    timeout = 120
    on-timeout = brightnessctl --device='backlight' get \
        || notify-send --app-name hypridle --expire-time 5000 \
        'Are you still there?' 'The monitors will be turned off in 30 seconds.'
}

# Trigger `lock_cmd`
listener {
    timeout = 150
    on-timeout = loginctl lock-session
}

# Turn off the screen after the session is locked
listener {
    timeout = 60
    condition_cmd = pidof hyprlock
    condition_retry = 60
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors && brightnessctl --restore
}

listener {
    timeout = 900
    on-timeout = systemctl suspend
}
