# $font = Sans
$font = Monospace

general {
  hide_cursor = true
  ignore_empty_input = true
}

# Swaylock-like input indicator
input-field {
  size = 180, 60
  hide_input = true
  outline_thickness = 5
  inner_color = rgba(0, 0, 0, 0.0)
}

# # Dot-masked text field
# input-field {
#   size = 350, 70
#   outline_thickness = 0
#   inner_color = rgba(255, 255, 255, 0.6)
#   dots_size = 0.2
#   placeholder_text =
# }

label {
  text = $TIME
  font_size = 80
  font_family = $font

  position = 0, 140
  halign = center
  valign = center
}

label {
  text = $LAYOUT
  font_family = $font

  position = 0, 140
  halign = center
  valign = bottom
}

background {
  # Impurity: Symlink the background picture imperatively in the wallpaper dir
  path = ~/Pictures/Wallpapers/hyprlock.background
  blur_passes = 3
  blur_size = 8
}

animations {
  animation = fade, 0, 10, default
}
